title: 先进集成电路材料与类脑芯片课题组 # 修改网站名称
baseURL: 'https://您的edgeone域名.com/' # 修改为您在EdgeOne绑定的域名

############################
## LANGUAGE
############################
defaultContentLanguage: zh # 默认语言改为中文
hasCJKLanguage: true # 开启中日韩语言字数统计支持
